# Site settings
languageCode = "en-us"
baseurl = "https://example.org/"
title = "Hugo fabric theme"
theme = "hugo-fabric"

[outputs]
home = [ "HTML", "RSS" ]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "atom"

[params]
  [params.theme]
    subtitle = "happy every day"
    post_type = "page" # For archive
    archive_post_type = "archives"

    # According to https://discuss.gohugo.io/t/how-to-access-the-top-level-rsslink-from-a-post/2044, we have to set this ourself
    site_rsslink = "atom.xml"

    # social account
    github_user = "wd"
    twitter_user = "wd"
    disqus_shortname = "wdicc"

    # post sharing
    facebook_like = true
    twitter_tweet_button = true
    google_plus_one = true
    google_plus_one_size = "midum"
    addthis_profile_id = "wd"
